version: '3'

services:
  database:
    image: postgres:16.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=findafriend